# Settings for detectomer

[zmq_sdr]
url = "tcp://localhost"
port = "5555"

[zmq_trigger]
url = "tcp://localhost"
port = "5556"

[data]
lframe = 2048
sample_rate = 2.048e6 # Hz, center frequency for the SDR
center_freq = 410e6   # Hz, center frequency for the SDR

[graph]
ymax = 10
ymin = -100
xmax = 1000
xmin = 0
yunit = "dBm"
xunit = "Hz"

[window]
xsize = 800
ysize = 600

[rest]
url = "tcp://localhost:5557"
SCID = 2222


