# Settings for detectomer

[zmq]
url = "tcp://localhost"
port = "5555"

[data]
lframe = 2048

[graph]
ymax = 10
ymin = -100
xmax = 1000
xmin = 0
yunit = "dBm"
xunit = "Hz"

[window]
xsize = 800
ysize = 600

[rest]
url = "tcp://localhost:5556"
SCID = 2222


